### ISSUE TITLE
A way to review submitted links.

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/tutorialdb#28]
Currently as soon as the link is submitted it gets live.
We need a way to not make it live unless until the admin checks it

**Comment by Animesh-Ghosh** [comment]
Maybe add a new field in the `tutorial` model which marks the tutorial as *"Under Review"* or *"Okayed"*. Then we can maybe open the links from the shell using `webbrowser` one by one, marking them as *"Okayed"* after reviewing the link.

Courses may get added just like that since they are only courses.

We may need to think about what kinds of tutorials we must let people add on the site. Categories may need some thinking. Some may need to be removed.

**Comment by Bhupesh-V** [comment]
@Animesh-Ghosh I guess we should close this one ?
