### ISSUE TITLE
AJAX autocomplete search suggestion for better search experience

### ISSUE THREAD

**Issue by techievivek** [Bhupesh-V/tutorialdb#81]
**Is your feature request related to a problem? Please describe.**
Thinking of Adding AJAX-based search suggestion for smooth search experience like one we see in google/YouTube.

**Describe the solution you'd like**
For every keypress(more than 2 characters), we can create an HTTP request and query database and if the result possible we can list them as links so the user can easily navigate through.

**Describe alternatives you've considered**
Or else we can cache the tags and if characters match with cached tags, we can redirect to the tag page. This will save the database querying.

**Additional context**

**Comment by VinitaNirmal** [comment]
I have a suggestion :

Whenever the page with Sercah box is openned there can be a deafult call to backend which returns the Most Viewed/Most Popular Courses like **6** courses of Java, **6** courses of React, **6** of Python etc.
When the user searches a keyword, we can show the data from this response and can giva link of show more options(If more java/react/python courses are available). If the user clicks on show more options then We can query tha database and get all the matches.
Since we are returning the most viewed Courses/Search queries there is a very less chance of DB Query.
